function fl_Q = flQ_Scalar_2D_ele(x1,x2,x3,y1,y2,y3)
%FLQ_SCALAR_2D_ELE
%    FL_Q = FLQ_SCALAR_2D_ELE(X1,X2,X3,Y1,Y2,Y3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Nov-2024 18:33:41

t2 = x1.*y2.*(1.0./6.0);
t3 = x3.*y1.*(1.0./6.0);
t4 = x2.*y3.*(1.0./6.0);
t6 = x2.*y1.*(1.0./6.0);
t7 = x1.*y3.*(1.0./6.0);
t8 = x3.*y2.*(1.0./6.0);
t5 = t2+t3+t4-t6-t7-t8;
fl_Q = [t5,t5,t5];
