function Mlm = MLM_Scalar_2D_ele(x1,x2,x3,y1,y2,y3)
%MLM_SCALAR_2D_ELE
%    MLM = MLM_SCALAR_2D_ELE(X1,X2,X3,Y1,Y2,Y3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    30-Nov-2024 18:33:40

t2 = x1.*y2.*(1.0./2.4e1);
t3 = x3.*y1.*(1.0./2.4e1);
t4 = x2.*y3.*(1.0./2.4e1);
t6 = x2.*y1.*(1.0./2.4e1);
t7 = x1.*y3.*(1.0./2.4e1);
t8 = x3.*y2.*(1.0./2.4e1);
t5 = t2+t3+t4-t6-t7-t8;
t9 = x1.*y2.*(1.0./1.2e1);
t10 = x3.*y1.*(1.0./1.2e1);
t11 = x2.*y3.*(1.0./1.2e1);
t13 = x2.*y1.*(1.0./1.2e1);
t14 = x1.*y3.*(1.0./1.2e1);
t15 = x3.*y2.*(1.0./1.2e1);
t12 = t9+t10+t11-t13-t14-t15;
Mlm = reshape([t12,t5,t5,t5,t12,t5,t5,t5,t12],[3,3]);
